{
 "title": "Home",
 "time": { "from": "2022-11-21T22:03:44.635Z", "to": "2022-11-21T22:22:54.663Z" },
 "panels": [
  {
   "title": "JOINT ANGLES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"development\")\r\n    |> range(start: -15m)\r\n    |> filter(fn: (r) => r._measurement == \"joint_1\" or r._measurement == \"joint_2\" or r._measurement == \"joint_3\" or r._measurement == \"joint_4\" or r._measurement == \"joint_5\" or r._measurement == \"joint_6\")\r\n"
    }
   ]
  },
  {
   "title": "DISK USE",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"development\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"fs\")\r\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"development\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"system\" and r._field == \"cpuLoadCurrent\")"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket:\"development\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"system\" and r._field == \"memActive\" or r._field == \"memFree\")"
    }
   ]
  },
  {
   "title": "GPU MEMORY USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"development\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"graphics\" and r._field == \"utilizationMemory\")\r\n"
    }
   ]
  },
  {
   "title": "GPU POWER DRAW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 22 },
   "targets": [
    {
     "query": "from(bucket:\"development\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"graphics\" and r._field == \"powerDraw\")"
    }
   ]
  },
  {
   "title": "GPU TEMPERATURE",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket:\"development\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"graphics\"  and r._field == \"temperatureGpu\")\r\n"
    }
   ]
  }
 ]
}